### ISSUE TITLE
Cloning SD cards

### ISSUE THREAD

**Issue by gbaman** [raspberrypilearning/teachers-classroom-guide#6]
One I get very frequently from teachers, "How do I clone an SD card".
They create a custom SD card image with all the extra bits they need for their class and want to put that on all their SD cards. As great as it would be to get the kids installing the software themselves, sometimes this just isn't possible due to time limitations or lack of internet.
Perhaps a mini guide on that in the teachers guide would be an idea?
Here is an already nearly complete one (created for a teacher few days ago) https://gist.github.com/gbaman/7a8b42a14b7fe4d25cdd although needs a few pictures.

**Comment by MissPhilbin** [comment]
Thanks for suggestions. We have updated the information on SD cards which should go live once it has been through copy edit.
